#!/usr/bin/env bash
# sync-docs-from-vault.sh
#
# One-way sync from the Obsidian vault subset (the SoT per DP-024) into this
# repo's docs/ tree. Run at sprint review (PROCESS §8 cadence) or whenever a
# DP / ADR / spec status transitions.
#
# Usage:
#   ./scripts/sync-docs-from-vault.sh [--dry-run]
#
# Assumes the vault is mounted at /Volumes/obsidian-vault (Chris's Mac default).
# Override with VAULT_ROOT env var.

set -euo pipefail

VAULT_ROOT="${VAULT_ROOT:-/Volumes/obsidian-vault}"
PROJECT_PATH="020 Projects/LLM-Cockpit"
SRC="$VAULT_ROOT/$PROJECT_PATH"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DST="$REPO_ROOT/docs"

DRY_RUN=""
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN="--dry-run"
fi

if [[ ! -d "$SRC" ]]; then
  echo "ERROR: vault subset not found at: $SRC" >&2
  echo "       set VAULT_ROOT or mount the vault first" >&2
  exit 2
fi

echo "Syncing $SRC -> $DST"

# rsync flags:
#   -a       archive mode (preserve everything)
#   -v       verbose
#   --delete remove files in DST not in SRC (the vault is SoT)
#   $DRY_RUN dry-run when requested
#
# We sync only the documented subset; we do NOT pull GOALS.md or README.md
# (those are project-overview docs that live in the vault only).
SUBDIRS=(
  "process"
  "decisions"
  "design-principles"
  "specs"
  "lessons-learned"
  "architecture"
  "use-cases"
)

for sd in "${SUBDIRS[@]}"; do
  if [[ -d "$SRC/$sd" ]]; then
    mkdir -p "$DST/$sd"
    rsync -av $DRY_RUN --delete \
      --exclude '.DS_Store' \
      --exclude '.obsidian' \
      --exclude '.smbdelete*' \
      "$SRC/$sd/" "$DST/$sd/"
  fi
done

# Stamp a sync-info file so it's clear when the mirror was last updated.
if [[ -z "$DRY_RUN" ]]; then
  cat > "$DST/SYNC.md" <<EOF
<!-- This file is auto-generated by scripts/sync-docs-from-vault.sh. Do not edit. -->
# Docs mirror — sync info

| Field | Value |
|---|---|
| Source | \`$VAULT_ROOT/$PROJECT_PATH\` |
| Synced at (UTC) | $(date -u +%Y-%m-%dT%H:%M:%SZ) |
| Synced by | $(whoami)@$(hostname) |
| Source HEAD (vault is not git, so this stays empty) | — |

The vault is the source of truth (DP-024). Don't edit anything in the synced subdirectories directly.
EOF
fi

echo "Done."
